### ISSUE TITLE
[OpenQA][Azure] - test fails on ansible saptune setup

### ISSUE THREAD

**Issue by lpalovsky** [SUSE/qe-sap-deployment#64]
Test fails upon setting up saptune. Issue seems to happen because saptune systemd service is not existing on SUT. 

```
 'fatal: [vmhana01]: FAILED! => {', '    "changed": false,', '    "invocation": {', '        "module_args": {', '            "daemon_reexec": false,', '            "daemon_reload": false,', '            "enabled": false,', '            "force": null,', '            "masked": null,', '            "name": "saptune",', '            "no_block": false,', '            "scope": "system",', '            "state": "stopped"', '        }', '    },', '    "msg": "Could not find the requested service saptune: host"', '}', '', 'PLAY RECAP *********************************************************************', 'vmhana01                   : ok=5    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   ', 'vmhana02                   : ok=5    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   ', '']
DEBUG:QESAPDEP:Ansible process return ret:2
ERROR:QESAPDEP:command:['ansible-playbook', '-vvvv', '-i', '/root/qe_sap_deployment/terraform/azure/inventory.yaml', '/root/qe_sap_deployment/ansible/playbooks/sap-hana-preconfigure.yaml', '-e', 'use_sapconf=True'] return not zero 2
ZaIUs-2-
``` 
Test: https://mordor.suse.cz/tests/4384#
Log files: https://mordor.suse.cz/tests/4384#downloads

**Comment by lpalovsky** [comment]
Problem might be in ansible checking for saptune sercive being disabled but fails since there is no saptune service present.

**Comment by lpalovsky** [comment]
Problem seems to be in ansible checking for saptune service being disabled but fails since there is no saptune service present.

**Comment by mr-stringer** [comment]
Which task is it failing on?  Is SAPCONF set to 'true' or 'false' when the runbook is called?

**Comment by lpalovsky** [comment]
Sapconf is set to 'true' and it is failing at sap-hana-preconfigure.yaml
```
DEBUG:QESAPDEP:Ansible process return ret:2
ERROR:QESAPDEP:command:['ansible-playbook', '-vvvv', '-i', '/root/qe_sap_deployment/terraform/azure/inventory.yaml', '/root/qe_sap_deployment/ansible/playbooks/sap-hana-preconfigure.yaml', '-e', 'use_sapconf=True'] return not zero 2
```

**Comment by mr-stringer** [comment]
With use_sapconf set to True, it'll try and use sapconf rather than saptune.  Is that what you want?

Anyway, here's where the sapconf code is doing.  We first try and figure out if saptune and tuned are installed

```yaml
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Set saptune installation status
  ansible.builtin.set_fact:
    saptune_inst: "{{ ansible_facts.packages.saptune[0].version | default('not-installed') }}"
    tuned_inst: "{{ ansible_facts.packages.tuned[0].version | default('not-installed') }}"
```

If saptune and/or tuned are not installed we set the fact to not-installed

If they are installed they get disabled.

```yaml
- name: Ensure saptune is stopped and disabled (if installed)
  ansible.builtin.systemd:
    name: saptune
    state: stopped
    enabled: no
  when: saptune_inst != 'not-installed'

- name: Ensure tuned is stopped and disabled (if installed)
  ansible.builtin.systemd:
    name: tuned
    state: stopped
    enabled: no
  when: tuned_inst != 'not-installed'
```

However, it's quite possible this code hasn't been fully tested.  I'll do some tests to make sure it's OK (which I suspect it isn't).

**Comment by lpalovsky** [comment]
Correct. use_sapconf = True
The problem is that after I logged into SUT the saptune package is installed but systemd does not see saptune service therefore it is failing. "systemctl status saptune" just says that service does not exist. 
The problem seems somewhere in the initial package. After I manually reinstalled the saptune package, systemd unit was suddenly there.

I was trying to add something like:

```
- name: Ensure saptune is uninstalled
  community.general.zypper:
    name: saptune
    state: removed
```

So it just removed the package, but it still went for the service check and failed.

**Comment by mr-stringer** [comment]
OK, that would work, but you'd need to refresh the facts as the facts were set while the package was still installed.  You could run the following again:

```yaml
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Set saptune installation status
  ansible.builtin.set_fact:
    saptune_inst: "{{ ansible_facts.packages.saptune[0].version | default('not-installed') }}"
    tuned_inst: "{{ ansible_facts.packages.tuned[0].version | default('not-installed') }}"
```

However, that doesn't feel too smart.  If we're happy to remove tuned and saptune regardless then the file could skip the package checking and fact setting and just remove the packages with something like:

```yaml
- name: Ensure needed packages are uninstalled
  community.general.zypper:
    name: "{{ item }}"
    state: removed
  loop:
    - saptune
    - tuned
```
This wouldn't fail if the packages are not installed, it would just report that nothing was changed.

However, it feels like the saptune package is a bit broken. It's installed but doesn't include the service :/

**Comment by lpalovsky** [comment]
Got another 'solution':
```
- name: Ensure saptune is on latest version. Fix for failing service check.
  community.general.zypper:
    name: saptune
    state: latest
```

Figured out that saptune was there but not updated. After update the service is visible and test continues until next failure :D
I am thinking about adding
 ```
   when: saptune_inst != 'not-installed'  
```
So it only does that if package is installed.
