### ISSUE TITLE
[GCP] generated Ansible inventory host labels has deployment_name from Terraform

### ISSUE THREAD

**Issue by mpagot** [SUSE/qe-sap-deployment#99]
Just for GCP, using glue script config.yaml like

```
provider: "gcp"
apiver: 2
terraform:
  variables:
    deployment_name: "mpagot"
  ...
```

Result generated inventory to looks like

```
all:
  children:
    hana:
      hosts:
        mpagot-vmhana01:
          ansible_host: *****
          ansible_python_interpreter: /usr/bin/python3 
        mpagot-vmhana02:
          ansible_host: *****
          ansible_python_interpreter: /usr/bin/python3 

  hosts: null
```

Expected inventory should look like

```
```
all:
  children:
    hana:
      hosts:
        vmhana01:
          ansible_host: *****
          ansible_python_interpreter: /usr/bin/python3 
        vmhana02:
          ansible_host: *****
          ansible_python_interpreter: /usr/bin/python3 

  hosts: null
```
